<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promise in javascript practice </title>
</head>
<body>
    
</body>
<script>
    const promiseone = new promise(function(resolve,reject){
        //do an async task
        // db calls ,cryptography,network
        setTimeout(function(){
            console.log('async task is completed');
            resolve()

        },1000)
    })

    promiseone.then(function(){
        console.log("promise consumed");

    })




      new promise(function(resolve,reject){
       
        setTimeout(function(){
            console.log('async task 2');
            resolve()

        },1000)
    })
     .then(function(){
        console.log("async 2 completed");

    })



   const  promisethree = new promise (function(resolve,reject){
    setTimeout(function(){
        resolve({username:"shubham",email:"shubhamkumarjha@gmail.com"})

    },1000)

   })
   promisethree.then(function(user){
    console.log(user);

   })


//    const promisefour = new promise(function(resolve,reject){
//     setTimeout(function(){
//         let error = false
//         if (!error) {
//             resolve({username:"hitesh",pasward:"123"})
            
//         }else{
//             reject('ERROR: something went wrong')
//         }
//     },1000)
//    })
//    promisefour.then((user)=>{
//     console.log(user)
//     return user.username
//    })
//    .then((username)=>{
//     console.log(username)
//    })
//    .catch(function(error){
//     console.log(error);
//    })
//    .finally(()=> console.log("the promise is either resolved or rejected"))


const promisefour = new promise(function(resolve,reject){
    setTimeout(function(){
        let error = true
        if (!error) {
            resolve({username:"hitesh",pasward:"123"})
            
        }else{
            reject('ERROR: something went wrong')
        }
    },1000)
   })
   promisefour.then((user)=>{
    console.log(user)
    return user.username
   })
   .then((username)=>{
    console.log(username)
   })
   .catch(function(error){
    console.log(error);
   })
   .finally(()=> console.log("the promise is either resolved or rejected"))




   const promisefive = new Promise((resolve, reject) => {
    setTimeout(function(){
        let error = true
        if (!error) {
            resolve({username:"shubham",pasward:"123"})
            
        }else{
            reject('ERROR: js went wrong')
        }
    },1000)
    
   });


   async function consumepromisefive(){
   try {
    const response = await promisefive
   console.log(response)
    
   } catch (error) {
    console.log(error)
    
   }

   }
   consumepromisefive()




//    async function  getallusers(){
//     try {
//         const response = await fetch('https://jsonplaceholder.typicode.com/users')
//         // console.log(response);
//        const data = await response.json()
//        console.log(data)
        
//     } catch (error) {
//         console.log("E:",error);
        
//     }
//    }
//    getallusers()



fetch('https://jsonplaceholder.typicode.com/users')
.then((response)=>{
    return response.json()

})
.then((data)=>{
    console.log(data);
})
.catch((error)=>console.log(error))
</script>
</html>